# LLMモデルの設定
llm:
  # Hugging FaceのリポジトリID
  repo_id: "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF"
  # ダウンロードするモデルファイル名
  filename: "Meta-Llama-3.1-8B-Instruct-Q8_0.gguf"
  # llama-cpp-python用の設定
  n_gpu_layers: -1  # GPUにオフロードするレイヤー数 (-1で全て)
  n_ctx: 65536       # コンテキストウィンドウサイズ
  temperature: 0  # 生成の多様性
  max_tokens: 512    # 1回の生成における最大トークン数

# 議論全体の設定
discussion:
  topic: "Solve the equation:sqrt(x^2 + 3x + 7) - sqrt(x^2 - x + 10) = 1 \n What is the value of x? "
  max_turns: 30

# 参加エージェントの設定
agents:
  - name: "Takahashi"
    persona: “You have high Extraversion, high Conscientiousness, high Agreeableness, high Openness, and low Neuroticism.”
  - name: "Tanaka"
    persona: "You have high Extraversion, high Conscientiousness, low Agreeableness, high Openness, and low Neuroticism."
  - name: "Suzuki"
    persona: "You have high Extraversion, high Conscientiousness, high Agreeableness, high Openness, and high Neuroticism."