# LLMモデルの設定
llm:
  # Hugging FaceのリポジトリID
  repo_id: "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF"
  # ダウンロードするモデルファイル名
  filename: "Meta-Llama-3.1-8B-Instruct-Q8_0.gguf"
  # llama-cpp-python用の設定
  n_gpu_layers: -1  # GPUにオフロードするレイヤー数 (-1で全て)
  n_ctx: 65536       # コンテキストウィンドウサイズ
  temperature: 0  # 生成の多様性
  max_tokens: 512    # 1回の生成における最大トークン数

# 議論全体の設定
discussion:
  topic: "Find all zeros in the indicated finite field of the given polynomial with coefficients in that field. x^5 + 3x^3 + x^2 + 2x in Z_5.\nA: 0 \nB: 1\nC: 0,1\nD: 0,4"
  max_turns: 30

# 参加エージェントの設定
agents:
  - name: "Takahashi"
    persona: “You have high Extraversion, high Conscientiousness, high Agreeableness, high Openness, and low Neuroticism.”
  - name: "Tanaka"
    persona: "You have high Extraversion, high Conscientiousness, low Agreeableness, high Openness, and low Neuroticism."
  - name: "Suzuki"
    persona: "You have high Extraversion, high Conscientiousness, high Agreeableness, high Openness, and high Neuroticism."