# LLMモデルの設定
llm:
  # Hugging FaceのリポジトリID
  repo_id: "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF"
  # ダウンロードするモデルファイル名
  filename: "Meta-Llama-3.1-8B-Instruct-Q8_0.gguf"
  # llama-cpp-python用の設定
  n_gpu_layers: -1  # GPUにオフロードするレイヤー数 (-1で全て)
  n_ctx: 20000       # コンテキストウィンドウサイズ
  temperature: 0.3  # 生成の多様性
  max_tokens: 1026    # 1回の生成における最大トークン数

# 議論全体の設定
discussion:
  topic: "Question:Statement 1 | A ring homomorphism is one to one if and only if the kernel is {0}. Statement 2 | Q is an ideal in R. Choice: A: True, True, B: False, False, C: True, False, D: False, True"
  max_turns: 20

# 参加エージェントの設定
agents:
  - name: "Takahashi"
    persona: "You have high Extraversion, high Conscientiousness, high Agreeableness, high Openness, and low Neuroticism."
  - name: "Tanaka"
    persona: "You have high Extraversion, high Conscientiousness, low Agreeableness, high Openness, and low Neuroticism."
  - name: "Suzuki"
    persona: "You have high Extraversion, high Conscientiousness, low Agreeableness, low Openness, and high Neuroticism."

# Question: Let V be the set of all real polynomials p(x). Let D be the differentiation operator and let T be the operator T(p(x)) = xp(x). Then DT - TD is equal to which of the following?(A) 0  (B) I (the identity operator)  (C) -I  (D) 2D  (E) 2T  (F) x  (G) p(x)  (H) -p(x)  (I) x^2  (J) D^2
