# LLMモデルの設定
llm:
  # Hugging FaceのリポジトリID
  repo_id: "bartowski/Meta-Llama-3.1-8B-Instruct-GGUF"
  # ダウンロードするモデルファイル名
  filename: "Meta-Llama-3.1-8B-Instruct-Q8_0.gguf"
  # llama-cpp-python用の設定
  n_gpu_layers: -1  # GPUにオフロードするレイヤー数 (-1で全て)
  n_ctx: 65536       # コンテキストウィンドウサイズ
  temperature: 0  # 生成の多様性
  max_tokens: 512    # 1回の生成における最大トークン数

# 議論全体の設定
discussion:
  topic: "Solve the equation:sqrt(x^2 + 3x + 7) - sqrt(x^2 - x + 10) = 1 \n What is the value of x? \n Please lead the value of x in the form of a decimal number."
  max_turns: 30

# 参加エージェントの設定
agents:
  - name: "Takahashi"
    persona: "You always take a critical perspective, looking for flaws in the arguments, and your remarks are consistently calm and logical."
  - name: "Tanaka"
    persona: "You are optimistic and enjoy discovering new possibilities."
  - name: "Suzuki"
    persona: "You aim to mediate between both sides, prevent the discussion from stagnating, and promote consensus, placing importance on overall balance."